version: '3.8'

services:
  app:
    container_name: boilerplate_adianti_app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        uid: 1000
    depends_on:
      - database
    volumes:
      - ./src/:/var/www/html
    networks:
      - boilerplate_adianti

  nginx:
    image: nginx:alpine
    container_name: boilerplate_adianti_nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - boilerplate_adianti

  database:
    container_name: boilerplate_adianti_db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./src/app/database/permission.sql:/docker-entrypoint-initdb.d/01.sql
      - ./src/app/database/communication.sql:/docker-entrypoint-initdb.d/02.sql
      - ./src/app/database/log.sql:/docker-entrypoint-initdb.d/03.sql
      - ./src/app/database/fix.sql:/docker-entrypoint-initdb.d/04.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate_adianti
    ports:
      - "5506:3306"
    networks:
      - boilerplate_adianti

networks:
  boilerplate_adianti:
    external: true
