version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        uid: 1000
    depends_on:
      - database
    volumes:
      - ./src/:/var/www/html
    ports:
      - "8080:80"
    networks:
      - system-admin

  database:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./src/app/database/permission.sql:/docker-entrypoint-initdb.d/01.sql
      - ./src/app/database/communication.sql:/docker-entrypoint-initdb.d/02.sql
      - ./src/app/database/log.sql:/docker-entrypoint-initdb.d/03.sql
      - ./src/app/database/fix.sql:/docker-entrypoint-initdb.d/04.sql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: system_admin
    ports:
        - "5506:3306"
    networks:
      - system-admin

networks:
  system-admin:
    external: true